# Generated by Django 5.2.15 on 2026-09-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Affiche / Image de couverture')),
                ('event_date', models.DateField(verbose_name="Date de l'événement")),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('location', models.CharField(default='Pissy, Ouagadougou', max_length=150, verbose_name='Lieu / Ville')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse précise')),
                ('capacity', models.PositiveIntegerField(default=100, help_text='0 pour illimité', verbose_name='Nombre de places maximales')),
                ('registration_enabled', models.BooleanField(default=True, verbose_name='Inscriptions ouvertes')),
                ('featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse email')),
                ('number_of_people', models.PositiveIntegerField(default=1, verbose_name='Nombre de personnes')),
                ('message', models.TextField(blank=True, verbose_name='Commentaire / Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Inscription événement',
                'verbose_name_plural': 'Inscriptions événements',
                'ordering': ['-created_at'],
            },
        ),
    ]
