# Generated by Django 5.2.15 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('summary', models.TextField(max_length=300, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Image de couverture')),
                ('objective', models.TextField(verbose_name='Objectifs principaux')),
                ('location', models.CharField(default='Ouagadougou, Burkina Faso', max_length=150, verbose_name="Zone d'impact")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin / Échéance')),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('ongoing', 'En cours'), ('completed', 'Terminé')], default='ongoing', max_length=20, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
