# Generated by Django 5.2.15 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOfAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du domaine')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-recycle', help_text='Ex: bi-trash, bi-tree, bi-palette, bi-trophy, bi-people, bi-calendar-event', max_length=60, verbose_name='Icône (Classe Bootstrap Icon)')),
                ('short_description', models.TextField(verbose_name='Description courte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Domaine d'action",
                'verbose_name_plural': "Domaines d'action",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Pissy Vibes', max_length=150, verbose_name='Nom du site')),
                ('tagline', models.CharField(default='Ensemble, on bouge, on nettoie et on fête.', max_length=255, verbose_name='Devise / Slogan')),
                ('vision', models.TextField(default='Contribuer à faire du Burkina Faso un pays plus propre et plus engagé, en plaçant l’art au service de la révolution environnementale.', verbose_name='Vision')),
                ('about_summary', models.TextField(default='Pissy Vibes est une association de jeunes engagés dans la promotion de l’assainissement, de l’environnement, de la culture et de la mobilisation citoyenne au Burkina Faso.', verbose_name='Présentation courte')),
                ('about_full_history', models.TextField(blank=True, default="Née au cœur du quartier de Pissy à Ouagadougou, Pissy Vibes rassemble une jeunesse dynamique déterminée à transformer son cadre de vie. Convaincue que l'engagement environnemental doit s'accompagner de joie, de créativité et de cohésion sociale, l'association a multiplié les opérations de salubrité publique, les reboisements et les rassemblements culturels pour éveiller les consciences.", verbose_name='Notre histoire complète')),
                ('mission', models.TextField(blank=True, default="Mobiliser, sensibiliser et outiller la jeunesse burkinabè pour agir concrètement en faveur de l'écologie urbaine, de l'assainissement durable et de l'épanouissement communautaire par la culture et le sport.", verbose_name='Notre mission')),
                ('email', models.EmailField(default='contact@pissyvibes.org', max_length=254, verbose_name='Email officiel')),
                ('phone', models.CharField(default='+226 70 00 00 00', max_length=50, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(default='+226 70 00 00 00', max_length=50, verbose_name='Numéro WhatsApp')),
                ('address', models.CharField(default='Secteur 17 (Pissy), Ouagadougou, Burkina Faso', max_length=255, verbose_name='Adresse')),
                ('opening_hours', models.CharField(default='Du Lundi au Samedi : 08h00 - 18h00', max_length=150, verbose_name="Horaires d'accueil")),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com', verbose_name='Lien Facebook')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com', verbose_name='Lien Instagram')),
                ('tiktok_url', models.URLField(blank=True, default='https://tiktok.com', verbose_name='Lien TikTok')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com', verbose_name='Lien YouTube')),
                ('twitter_url', models.URLField(blank=True, default='https://x.com', verbose_name='Lien X (Twitter)')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com', verbose_name='Lien LinkedIn')),
                ('stat_actions_count', models.PositiveIntegerField(default=48, verbose_name='Actions réalisées')),
                ('stat_volunteers_count', models.PositiveIntegerField(default=420, verbose_name='Jeunes mobilisés')),
                ('stat_trees_planted', models.PositiveIntegerField(default=1500, verbose_name='Arbres plantés')),
                ('stat_neighborhoods_count', models.PositiveIntegerField(default=14, verbose_name='Quartiers touchés')),
                ('stat_events_count', models.PositiveIntegerField(default=32, verbose_name='Événements organisés')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo principal')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Logo version sombre')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Favicon')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Image Hero Homepage')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
