# Generated by Django 5.2.15 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'action")),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Résumé court')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='actions/', verbose_name='Image de couverture')),
                ('category', models.CharField(choices=[('assainissement', 'Assainissement'), ('environnement', 'Environnement'), ('culture', 'Culture'), ('sport', 'Sport'), ('citoyennete', 'Citoyenneté'), ('communaute', 'Communauté')], default='assainissement', max_length=30, verbose_name='Catégorie')),
                ('location', models.CharField(default='Pissy, Ouagadougou', max_length=150, verbose_name='Lieu / Quartier')),
                ('date', models.DateField(verbose_name="Date de l'action")),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Réalisée')], default='completed', max_length=20, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name="Mise en avant sur l'accueil")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
