# Generated by Django 5.2.15 on 2026-09-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Titre de l'album")),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name="Description de l'album")),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Image de couverture')),
                ('date', models.DateField(blank=True, null=True, verbose_name="Date de l'événement lié")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Album Photo',
                'verbose_name_plural': 'Albums Photos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la vidéo')),
                ('video_url', models.URLField(help_text='Ex: https://www.youtube.com/watch?v=XXXX ou https://vimeo.com/XXXX', verbose_name='Lien YouTube ou Vimeo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/videos/', verbose_name='Miniature personnalisée')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Titre / Légende')),
                ('image', models.ImageField(upload_to='gallery/photos/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('alt_text', models.CharField(default="Photo d'activité Pissy Vibes", max_length=200, verbose_name='Texte alternatif (Accessibilité SEO)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date de prise de vue')),
                ('featured', models.BooleanField(default=False, verbose_name='Mettre en avant sur la homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.galleryalbum', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
