# Generated by Django 5.2.15 on 2026-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Téléversez un fichier vidéo local ou indiquez un lien YouTube/Vimeo ci-dessous.', null=True, upload_to='gallery/videos_files/', verbose_name='Fichier vidéo local (MP4, WebM...)'),
        ),
        migrations.AlterField(
            model_name='galleryvideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Ex: https://www.youtube.com/watch?v=XXXX ou https://vimeo.com/XXXX', verbose_name='Lien YouTube ou Vimeo'),
        ),
    ]
