# Generated by Django 5.2.15 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo de profil')),
                ('role', models.CharField(help_text='Ex: Président, Responsable Salubrité, Chargé de Com...', max_length=150, verbose_name='Rôle / Fonction')),
                ('bio', models.TextField(blank=True, verbose_name='Courte biographie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (Affichage public)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone (Affichage public)')),
                ('facebook', models.URLField(blank=True, verbose_name='Lien Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Lien Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='Lien LinkedIn')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['display_order', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom de la personne')),
                ('role', models.CharField(default='Bénévole engagé', help_text='Ex: Riverain de Pissy, Volontaire, Partenaire...', max_length=150, verbose_name='Titre / Qualité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Note (étoiles 1-5)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
