# Generated by Django 5.2.15 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone', models.CharField(max_length=50, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse email')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('city_neighborhood', models.CharField(default='Ouagadougou, Pissy', max_length=150, verbose_name='Ville / Quartier de résidence')),
                ('interest_domain', models.CharField(choices=[('environnement', 'Environnement & Reboisement'), ('assainissement', 'Assainissement & Salubrité urbaine'), ('culture', 'Culture, Art & Musique'), ('sport', 'Sport & Animations jeunesse'), ('communication', 'Communication & Réseaux sociaux'), ('organisation', 'Logistique & Organisation d’événements'), ('media', 'Photographie / Vidéo'), ('general', 'Bénévolat général / Polyvalent')], default='assainissement', max_length=40, verbose_name="Domaine d'intérêt principal")),
                ('availability', models.CharField(default='Week-ends', help_text='Ex: Week-ends, En semaine, Événements ponctuels...', max_length=100, verbose_name='Disponibilité')),
                ('message', models.TextField(blank=True, verbose_name='Pourquoi souhaites-tu rejoindre Pissy Vibes ?')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Contacté(e)'), ('accepted', 'Intégré(e)'), ('archived', 'Archivé(e)')], default='pending', max_length=20, verbose_name='Statut de traitement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Candidature envoyée le')),
            ],
            options={
                'verbose_name': 'Candidature bénévole',
                'verbose_name_plural': 'Candidatures bénévoles',
                'ordering': ['-created_at'],
            },
        ),
    ]
